// generated by Fast Light User Interface Designer (fluid) version 1.0303

#ifndef dlg_h
#define dlg_h
#include <FL/Fl.H>
/**
   in header
*/
#include "input_slider.h"
/**
   in header
*/
#include "int_input.h"
/**
   in header
*/
#include "lrs_view.h"
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Tabs.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Box.H>
#include <FL/Fl_Value_Slider.H>

class Main_UI {
public:
  Main_UI();
private:
  Fl_Double_Window *main_window;
  Fl_Tabs *tabs_param;
  Lrs_view *lrs_view;
  Fl_Value_Slider *eps_slider;
  inline void cb_eps_slider_i(Fl_Value_Slider*, void*);
  static void cb_eps_slider(Fl_Value_Slider*, void*);
public:
  void show(int argc, char* argv[]);
  float eps();
};
#endif
