// generated by Fast Light User Interface Designer (fluid) version 1.0303

#include "dlg.h"

void Main_UI::cb_eps_slider_i(Fl_Value_Slider*, void*) {
  lrs_view->redraw();
}
void Main_UI::cb_eps_slider(Fl_Value_Slider* o, void* v) {
  ((Main_UI*)(o->parent()->user_data()))->cb_eps_slider_i(o,v);
}

Main_UI::Main_UI() {
  { main_window = new Fl_Double_Window(708, 495, "\320\234\320\276\320\264\320\265\320\273\321\214 \320\240\320\233\320\241");
    main_window->user_data((void*)(this));
    { tabs_param = new Fl_Tabs(435, 15, 265, 475);
      { Fl_Group* o = new Fl_Group(435, 30, 265, 460, "Option1");
        o->hide();
        { Fl_Box* o = new Fl_Box(440, 36, 250, 94, "\320\232\320\276\320\276\321\200\320\264\320\270\320\275\320\260\321\202\321\
\213 \321\202\320\276\321\207\320\272\320\270 \321\201\321\202\320\276\321\
\217\320\275\320\270\321\217 \320\240\320\233\320\241 \320\262 \320\223\320\
\241\320\232, \320\263\321\200");
          o->box(FL_THIN_UP_BOX);
          o->labelfont(1);
          o->labelsize(12);
          o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { Int_input* o = new Int_input(645, 51, 40, 24, "\320\223\320\265\320\276\320\263\321\200\320\260\321\204\320\270\321\207\320\
\265\321\201\320\272\320\260\321\217 \320\264\320\276\320\273\320\263\320\276\
\321\202\320\260:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->maximum(90);
          o->step(1);
          o->value(90);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 76, 40, 24, "\320\223\320\265\320\276\320\263\321\200\320\260\321\204\320\270\321\207\320\
\265\321\201\320\272\320\260\321\217 \321\210\320\270\321\200\320\276\321\202\
\320\260:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->maximum(90);
          o->step(1);
          o->value(65);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 101, 40, 24, "\320\243\320\263\320\276\320\273 \320\277\320\276\320\262\320\276\321\200\
\320\276\321\202\320\260 \320\276\321\201\320\270 Z \320\234\320\237\320\241\
\320\232:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->minimum(-360);
          o->maximum(360);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 135, 40, 24, "\320\240\320\260\320\261\320\276\321\207\320\260\321\217 \321\207\320\260\
\321\201\321\202\320\276\321\202\320\260 \320\240\320\233\320\241, \320\234\
\320\223\321\206:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->maximum(10000);
          o->value(600);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Fl_Box* o = new Fl_Box(440, 163, 250, 175, "\320\240\320\260\320\267\320\274\320\265\321\200\321\213 \320\277\320\265\
\321\200\320\265\320\264\320\260\321\216\321\211\320\265\320\271 \320\270 \
\320\277\321\200\320\270\321\221\320\274\320\275\320\276\320\271 \320\244\320\
\220\320\240, \320\274");
          o->box(FL_THIN_UP_BOX);
          o->labelfont(1);
          o->labelsize(13);
          o->align(Fl_Align(129|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { Int_input* o = new Int_input(645, 190, 40, 24, "\320\237\320\265\321\200\320\265\320\264\320\260\321\216\321\211\320\265\320\
\271 \320\277\320\276 \320\263\320\276\321\200\320\270\320\267\320\276\320\
\275\321\202\320\260\320\273\320\270:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->minimum(1);
          o->maximum(1000);
          o->value(20);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 236, 40, 24, "\320\237\321\200\320\270\321\221\320\274\320\275\320\276\320\271 \320\277\
\320\276 \320\263\320\276\321\200\320\270\320\267\320\276\320\275\321\202\320\
\260\320\273\320\270:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->minimum(1);
          o->maximum(1000);
          o->value(40);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 213, 40, 24, "\320\237\320\265\321\200\320\265\320\264\320\260\321\216\321\211\320\265\320\
\271 \320\277\320\276 \320\262\320\265\321\200\321\202\320\270\320\272\320\
\260\320\273\320\270:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->minimum(1);
          o->maximum(1000);
          o->value(30);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 259, 40, 24, "\320\237\321\200\320\270\321\221\320\274\320\275\320\276\320\271 \320\277\
\320\276 \320\262\320\265\321\200\321\202\320\270\320\272\320\260\320\273\320\
\270:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(40);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 296, 40, 24, "\320\243\320\263\320\276\320\273 \320\275\320\260\320\272\320\273\320\276\
\320\275\320\260 \320\277\320\276\320\273\320\276\321\202\320\275\320\260 \
\320\244\320\220\320\240, \320\276\321\202\320\275\320\276\321\201\320\270\
\321\202\320\265\320\273\321\214\320\275\320\276 \320\267\320\265\320\274\320\
\275\320\276\320\271 \320\277\320\276\320\262\320\265\321\200\321\205\320\275\
\320\276\321\201\321\202\320\270, \320\263\321\200\320\260\320\264\321\203\
\321\201\321\213:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(70);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Fl_Box* o = new Fl_Box(440, 342, 250, 138, "\320\240\320\260\320\267\320\274\320\265\321\200\321\213 \320\267\320\276\
\320\275\321\213 \320\276\320\261\320\267\320\276\321\200\320\260 \320\240\
\320\233\320\241, \320\263\321\200\320\260\320\264\321\203\321\201\321\213");
          o->box(FL_THIN_UP_BOX);
          o->labelfont(1);
          o->labelsize(13);
          o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { Int_input* o = new Int_input(645, 362, 40, 24, "\320\235\320\270\320\266\320\275\321\217\321\217 \320\263\321\200\320\260\
\320\275\320\270\321\206\320\260 \320\267\320\276\320\275\321\213 \320\276\
\320\261\320\267\320\276\321\200\320\260 \320\277\320\276 \320\260\320\267\
\320\270\320\274\321\203\321\202\321\203:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(-45);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 391, 40, 24, "\320\222\320\265\321\200\321\205\320\275\321\217\321\217 \320\263\321\200\
\320\260\320\275\320\270\321\206\320\260 \320\267\320\276\320\275\321\213 \
\320\276\320\261\320\267\320\276\321\200\320\260 \320\277\320\276 \320\260\
\320\267\320\270\320\274\321\203\321\202\321\203:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(45);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 419, 40, 24, "\320\235\320\270\320\266\320\275\321\217\321\217 \320\263\321\200\320\260\
\320\275\320\270\321\206\320\260 \320\276\320\261\320\267\320\276\321\200\320\
\260 \320\277\320\276 \321\203\320\263\320\273\321\203 \320\274\320\265\321\
\201\321\202\320\260:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(10);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 446, 40, 24, "\320\222\320\265\321\200\321\205\320\275\321\217\321\217 \320\263\321\200\
\320\260\320\275\320\270\321\206\320\260 \320\267\320\276\320\275\321\213 \
\320\276\320\261\320\267\320\276\321\200\320\260 \320\277\320\276 \321\203\
\320\263\320\273\321\203 \320\274\320\265\321\201\321\202:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(60);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(435, 30, 265, 460, "Option2");
        { Fl_Box* o = new Fl_Box(440, 37, 250, 113, "\320\232\320\230\320\237 \320\270 \320\232\320\220\320\240 \320\244\320\220\
\320\240");
          o->box(FL_THIN_UP_BOX);
          o->labelfont(1);
          o->labelsize(12);
          o->align(Fl_Align(FL_ALIGN_TOP|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { Int_input* o = new Int_input(645, 51, 40, 24, "\320\232\320\230\320\237 \320\277\320\265\321\200\320\265\320\264\320\260\
\321\216\321\211\320\265\320\271 \320\244\320\220\320\240:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(0.99);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
          o->deactivate();
        } // Int_input* o
        { Int_input* o = new Int_input(645, 75, 40, 24, "\320\232\320\220\320\240 \320\277\320\265\321\200\320\265\320\264\320\260\
\321\216\321\211\320\265\320\271 \320\244\320\220\320\240:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(50);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
          o->deactivate();
        } // Int_input* o
        { Int_input* o = new Int_input(645, 98, 40, 24, "\320\232\320\230\320\237 \320\277\321\200\320\270\321\221\320\274\320\275\
\320\276\320\271 \320\244\320\220\320\240:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(0.99);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
          o->deactivate();
        } // Int_input* o
        { Int_input* o = new Int_input(645, 121, 40, 24, "\320\232\320\220\320\240 \320\277\321\200\320\270\321\221\320\274\320\275\
\320\276\320\271 \320\244\320\220\320\240:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(14);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(50);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
          o->deactivate();
        } // Int_input* o
        { Fl_Box* o = new Fl_Box(440, 157, 250, 214, "\320\237\320\260\321\200\320\260\320\274\320\265\321\202\321\200\321\213 \
\320\264\320\273\321\217 \321\200\320\260\321\201\321\207\320\265\321\202\320\
\260 \321\215\320\275\320\265\321\200\320\263\320\265\321\202\320\270\321\207\
\320\265\321\201\320\272\320\270\321\205 \321\205\320\260\321\200\320\260\320\
\272\321\202\320\265\321\200\320\270\321\201\321\202\320\270\320\272 \320\240\
\320\233\320\241");
          o->box(FL_THIN_UP_BOX);
          o->labelfont(1);
          o->labelsize(12);
          o->align(Fl_Align(129|FL_ALIGN_INSIDE));
        } // Fl_Box* o
        { Int_input* o = new Int_input(645, 194, 40, 24, "\320\234\320\276\321\211\320\275\320\276\321\201\321\202\321\214 \320\276\
\320\264\320\275\320\276\320\263\320\276 \320\277\320\265\321\200\320\265\320\
\264\320\260\321\216\321\211\320\265\320\263\320\276 \320\274\320\276\320\264\
\321\203\320\273\321\217, \320\222\321\202:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(600);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 222, 40, 24, "\320\241\320\272\320\262\320\260\320\266\320\275\320\276\321\201\321\202\321\
\214 \321\201\320\273\320\265\320\264\320\276\320\262\320\260\320\275\320\270\
\321\217 \320\270\320\274\320\277\321\203\320\273\321\214\321\201\320\276\320\
\262:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(10);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(645, 250, 40, 24, "\320\232\320\276\320\273\320\270\321\207\320\265\321\201\321\202\320\262\320\
\276 \320\275\320\260\320\272\320\260\320\277\320\273\320\270\320\262\320\260\
\320\265\320\274\321\213\321\205 \320\276\321\202\321\200\320\260\320\266\321\
\221\320\275\320\275\321\213\321\205 \320\276\321\202 \321\206\320\265\320\
\273\320\270 \320\270\320\274\320\277\321\203\320\273\321\214\321\201\320\276\
\320\262:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(1);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(644, 279, 40, 24, "\320\222\320\265\321\200\320\276\321\217\321\202\320\275\320\276\321\201\321\
\202\321\214 \320\277\321\200\320\260\320\262\320\270\320\273\321\214\320\275\
\320\276\320\263\320\276 \320\276\320\261\320\275\320\260\321\200\321\203\320\
\266\320\265\320\275\320\270\321\217:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(0.95);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(644, 308, 40, 24, "\320\222\320\265\321\200\320\276\321\217\321\202\320\275\320\276\321\201\321\
\202\321\214 \320\273\320\276\320\266\320\275\320\276\320\271 \321\202\321\
\200\320\265\320\262\320\276\320\263\320\270, 10^-6:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(1);
          o->align(Fl_Align(132));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        { Int_input* o = new Int_input(644, 337, 40, 24, "\320\255\320\237\320\240 \321\206\320\265\320\273\320\270, \320\274^2:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(13);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->value(1);
          o->align(Fl_Align(FL_ALIGN_LEFT));
          o->when(FL_WHEN_CHANGED);
        } // Int_input* o
        o->end();
      } // Fl_Group* o
      tabs_param->end();
    } // Fl_Tabs* tabs_param
    { lrs_view = new Lrs_view(15, 15, 415, 445);
      lrs_view->box(FL_UP_BOX);
      lrs_view->color(FL_BACKGROUND_COLOR);
      lrs_view->selection_color(FL_BACKGROUND_COLOR);
      lrs_view->labeltype(FL_NORMAL_LABEL);
      lrs_view->labelfont(0);
      lrs_view->labelsize(14);
      lrs_view->labelcolor(FL_FOREGROUND_COLOR);
      lrs_view->align(Fl_Align(FL_ALIGN_CENTER));
      lrs_view->when(FL_WHEN_RELEASE);
    } // Lrs_view* lrs_view
    { eps_slider = new Fl_Value_Slider(15, 465, 415, 25, "eps");
      eps_slider->type(1);
      eps_slider->labelsize(8);
      eps_slider->minimum(-45);
      eps_slider->maximum(45);
      eps_slider->textsize(14);
      eps_slider->callback((Fl_Callback*)cb_eps_slider);
      eps_slider->align(Fl_Align(FL_ALIGN_LEFT));
    } // Fl_Value_Slider* eps_slider
    main_window->end();
  } // Fl_Double_Window* main_window
}

void Main_UI::show(int argc, char* argv[]) {
  main_window->show(argc,argv);
}

float Main_UI::eps() {
  return eps_slider->value();
}
